export const profile = {
  name: "Nicolas Stirnemann",
  handle: "BatmiBoom",
  role: "Software Engineer",
  company: "BrainHi",
  location: "La Plata, Argentina",
  summary: "Software engineer building practical systems, developer tooling, games, automation, and experiments across Go, Lua, Python, Astro, Rust, D, GDScript, and more.",
  avatar: "https://avatars.githubusercontent.com/u/47833971?v=4",
  links: [
    ["GitHub", "https://github.com/BatmiBoom"],
    ["LinkedIn", "https://www.linkedin.com/in/nstirnemann/"],
  ],
  stats: [["36", "public repos"], ["8+", "languages"], ["2019", "on GitHub"], ["BrainHi", "current company"]],
  nav: [["Work", "#work"], ["Projects", "#projects"], ["Principles", "#principles"], ["Contact", "#contact"]],
  work: [["BrainHi", "Software Engineer"], ["Open source", "Developer tools, configs, games, and learning projects"], ["LinkedIn", "La Plata profile with BrainHi, previous experience, and education listed"]],
  stack: ["Go", "Lua", "Python", "Astro", "Rust", "D", "GDScript", "Shell"],
  terminal: ["nvim / ghostty / wezterm configs", "Go servers, crawlers, CLIs", "Godot and Love2D game experiments", "notes on infra, SQL, AWS, algorithms"],
  projects: [
    ["PersonalPage", "Astro personal site with GitHub Pages deployment.", "Astro", "https://github.com/BatmiBoom/PersonalPage"],
    ["AndroidGame", "Godot/Android game inspired by viral mobile game loops.", "Godot", "https://github.com/BatmiBoom/AndroidGame"],
    ["nvim", "Neovim setup tuned around daily engineering workflow.", "Lua", "https://github.com/BatmiBoom/nvim"],
    ["notes", "Personal notes on languages, tools, algorithms, infra, HTTP, SQL, AWS, architecture, and game dev.", "C / docs", "https://github.com/BatmiBoom/notes"],
    ["AiAgent", "Agent similar to Claude Code.", "AI tooling", "https://github.com/BatmiBoom/AiAgent"],
    ["BlogAggregator", "Backend learning project written in Go.", "Go", "https://github.com/BatmiBoom/BlogAggregator"],
  ],
  principles: ["Small APIs", "DRY after the pattern is real", "SOLID where it lowers change cost", "Readable code over clever code"],
} as const;
